{
    'name': 'IT Mall Branding',
    'version': '18.0.1.0.0',
    'category': 'Customization',
    'summary': 'IT Mall enterprise branding, debranding and custom dark theme',
    'author': 'IT Mall',
    'website': 'https://itmall.ma',
    'license': 'LGPL-3',
    'depends': [
        'web',
        'mail',
        'crm',
        'sale_management',
        'stock',
        'account',
        'purchase',
        'calendar',
    ],
    'data': [
        'security/ir.model.access.csv',
        'security/security_rules.xml',
        'data/config.xml',
        'data/products.xml',
        'data/crm_stages.xml',
        'views/actions.xml',
        'views/branding_templates.xml',
        'views/email_templates.xml',
        'views/password_wizard.xml',
        'views/user_form.xml',
        'views/webclient_templates.xml',
        'views/call_log_views.xml',
        'views/partner_views.xml',
        'views/res_config_settings_views.xml',
        'views/report_saleorder.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'it_mall_branding/static/src/scss/main.scss',
            'it_mall_branding/static/src/js/debrand.js',
            'it_mall_branding/static/src/js/sidebar.js',
            'it_mall_branding/static/src/js/user_menu_activities.js',
            'it_mall_branding/static/src/js/crm_kanban_patch.js',
            'it_mall_branding/static/src/js/welcome_page.js',
            'it_mall_branding/static/src/xml/debrand.xml',
            'it_mall_branding/static/src/xml/sidebar.xml',
            'it_mall_branding/static/src/xml/welcome_page.xml',
            'it_mall_branding/static/src/xml/form_buttons.xml',
        ],
    },
    'installable': True,
    'application': True,
    'auto_install': False,
}
